server:
  port: 8069
  compression:
    # 开启 GZIP
    enabled: true
  servlet:
    context-path: /ringinterviewapi

##数据源配置
spring:

  profiles:
    active: dev

  application:
    name: ring-interview-api
  output:
    ansi:
      enabled: ALWAYS

  resources:
    static-locations: classpath:/META-INF/resources/webjars/,classpath:/META-INF/resources/,file:/Users/monetware/Desktop/ringinterview/files/,file:D:/Users/monetware/Desktop/ringinterview/files/,file:E:/Simo/Common/ringinterview/files/

  ## 数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver


    ## druid连接池
    druid:
      stat-view-servlet:
        login-username: monetware
        login-password: mt2018
        allow: "127.0.0.1"
    filter:
      slf4j:
        enabled: true

  ## 文件上传限制大小
  servlet:
    multipart:
      max-file-size: 400MB
      max-request-size: 400MB
      enabled: true

    ## redis配置
    # REDIS (RedisProperties)
    # Redis数据库索引（默认为0）
  redis:
    database: 0
    timeout: 5000
    # Redis服务器地址
    host: 175.102.15.229
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制）
#    pool:
#      max-active: 8
#      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-wait: -1
#      # 连接池中的最大空闲连接
#      max-idle: 8
#      # 连接池中的最小空闲连接
#      min-idle: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml
  ##驼峰匹配
  configuration:
    map-underscore-to-camel-case: true

## 通用mapper配置
mapper:
  mappers: com.monetware.ringinterview.system.base.MyMapper
  not-empty: false
  identity: MYSQL

## pageHelper配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: false
  params: count=countSql

## 日志处理
logging:
  level:
    io.swagger.models.parameters: error
    ## 输出sql日志
    com.monetware.ringinterview.business.dao: debug
    org.springframework.web.client: debug
  logdir: /Users/budi/Desktop/monetware/ring-interview-api/logs
  appname: ring-interview-api






